services:
  laravel-api-app:
    build:
      context: ./php
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - ./laravel:/var/www
    networks:
      - laravel

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./laravel/public:/var/www/public:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - laravel-api-app
    networks:
      - laravel

networks:
  laravel:

