services:
  laravel-api-app:
    dns:
      - 8.8.8.8
    build:
      context: .                    # full project context
      dockerfile: php/Dockerfile   # Dockerfile still in php/
    container_name: laravel-app
    working_dir: /var/www
      # volumes:
      # - ./laravel:/var/www         # good for development
    command: php-fpm
    networks:
      - laravel-network

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./laravel/public:/var/www/public:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - laravel-api-app
    networks:
      - laravel-network

  mysql:
    image: mysql:8
    container_name: mysql-dev-temp
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: 41818
    volumes:
      - /var/lib/mysql               # anonymous volume (no named volume = temporary)
    networks:
      - laravel-network

networks:
  laravel-network:
    external: true

